name: 'ontario_grid'
version: '1.0.0'
config-version: 2

profile: 'ontario_grid'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ontario_grid:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
